<a href="https://colab.research.google.com/github/srividyaprasad/pesu_io_ml/blob/main/Customer_Churn_Prediction_by_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Logistic Regression 

In [ ]:
!pip install scikit-learn==0.23.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 6.8 MB 9.5 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.23.1 which is incompatible.
imbalanced-learn 0.8.1 requires scikit-learn>=0.24, but you have scikit-learn 0.23.1 which is incompatible.


In [ ]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

Telecommunications dataset for predicting customer churn. This is a historical customer dataset where each row represents one customer. Typically it is less expensive to keep customers than acquire new ones, so the focus of this analysis is to predict the customers who will stay with the company. 

This data set provides information to help you predict what behavior will help you to retain customers. You can analyze all relevant customer data and develop focused customer retention programs.

The dataset includes info about:

*   Customers who left within the last month – the column is called Churn
*   Services that each customer has signed up for – phone, multiple lines, internet, online security, online backup, device protection, tech support, and streaming TV and movies
*   Customer account information – how long they had been a customer, contract, payment method, paperless billing, monthly charges, and total charges
*   Demographic info about customers – gender, age range, and if they have partners and dependents

In [ ]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv")
display(df)
df.info()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
..      ...   ...      ...     ...  ...     ...    ...       ...       ...   
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0       1.0       0.0   
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0       4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1       9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2       6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3       6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4       7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   
..       ...  ...    ...       ...       ...     ...    ...      ...      ...   
195    17.35  ...    0.0       0.0       0.0     1.0    0.0    2.854    3.199   
196     6.00  ...    0.0       0.0       1.0     1.0    0.0    1.792    3.332   
197     3.85  ...    0.0       0.0       1.0     1.0    0.0    1.348    3.168   
198     8.70  ...    1.0       1.0       1.0     1.0    1.0    2.163    3.866   
199    16.85  ...    0.0       1.0       0.0     0.0    1.0    2.824    3.240   

     lninc  custcat  churn  
0    4.913      4.0    1.0  
1    3.497      1.0    1.0  
2    3.401      3.0    0.0  
3    4.331      4.0    0.0  
4    4.382      3.0    0.0  
..     ...      ...    ...  
195  4.419      3.0    0.0  
196  3.178      3.0    0.0  
197  3.850      3.0    0.0  
198  3.219      4.0    1.0  
199  5.247      2.0    0.0  

[200 rows x 28 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 28 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   tenure    200 non-null    float64
 1   age       200 non-null    float64
 2   address   200 non-null    float64
 3   income    200 non-null    float64
 4   ed        200 non-null    float64
 5   employ    200 non-null    float64
 6   equip     200 non-null    float64
 7   callcard  200 non-null    float64
 8   wireless  200 non-null    float64
 9   longmon   200 non-null    float64
 10  tollmon   200 non-null    float64
 11  equipmon  200 non-null    float64
 12  cardmon   200 non-null    float64
 13  wiremon   200 non-null    float64
 14  longten   200 non-null    float64
 15  tollten   200 non-null    float64
 16  cardten   200 non-null    float64
 17  voice     200 non-null    float64
 18  pager     200 non-null    float64
 19  internet  200 non-null    float64
 20  callwait  200 non-null    float6

In [ ]:
churn_df = df[['tenure', 'age', 'address', 'income']]
churn_df['income'] = churn_df['income'].astype('int')
churn_df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


tenure   age  address  income
0    11.0  33.0      7.0     136
1    33.0  33.0     12.0      33
2    23.0  30.0      9.0      30
3    38.0  35.0      5.0      76
4     7.0  35.0     14.0      80

In [ ]:
X = np.asanyarray(churn_df[['tenure', 'age', 'address', 'income']])
X[0:5]

array([[ 11.,  33.,   7., 136.],
       [ 33.,  33.,  12.,  33.],
       [ 23.,  30.,   9.,  30.],
       [ 38.,  35.,   5.,  76.],
       [  7.,  35.,  14.,  80.]])

In [ ]:
y = np.asanyarray(df['churn'])
y [0:5]

array([1., 1., 0., 0., 0.])

Also, we normalize the dataset:

In [ ]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
# std value = (x-myu)/sigma where myu is mean, sigma is variance
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451]])

## Train/Test dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 4) (160,)
Test set: (40, 4) (40,)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train) #c=regularisation= 1-error  (checking errors)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [ ]:
yhat = LR.predict(X_test)
yhat

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 0.])

**predict_proba**  returns estimates for all classes, ordered by the label of classes. So, the first column is the probability of class 0, P(Y=0|X), and second column is probability of class 1, P(Y=1|X):

In [ ]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.5977768 , 0.4022232 ],
       [0.56107912, 0.43892088],
       [0.50596735, 0.49403265],
       [0.58353634, 0.41646366],
       [0.54570682, 0.45429318],
       [0.50669861, 0.49330139],
       [0.51759306, 0.48240694],
       [0.54007336, 0.45992664],
       [0.47670896, 0.52329104],
       [0.60062903, 0.39937097],
       [0.64401478, 0.35598522],
       [0.64317531, 0.35682469],
       [0.44345131, 0.55654869],
       [0.49208001, 0.50791999],
       [0.57517166, 0.42482834],
       [0.55587005, 0.44412995],
       [0.59708117, 0.40291883],
       [0.56344291, 0.43655709],
       [0.57515736, 0.42484264],
       [0.51949283, 0.48050717],
       [0.57308371, 0.42691629],
       [0.59592059, 0.40407941],
       [0.60239628, 0.39760372],
       [0.58035783, 0.41964217],
       [0.53254911, 0.46745089],
       [0.66725746, 0.33274254],
       [0.5396121 , 0.4603879 ],
       [0.5646213 , 0.4353787 ],
       [0.48685578, 0.51314422],
       [0.67942928, 0.32057072],
       [0.

In [ ]:
arr = confusion_matrix(y_test, yhat)
# tp fp
# fn tn

In [ ]:
#start here 
print((arr[0][0]+arr[1][1])/(arr[0][0]+arr[1][0]+arr[0][1]+arr[1][1]))

0.7


<h1>Project 2 </h1>


In [ ]:
dff=df
display(dff)
X = np.asanyarray(dff[["address","internet", "callcard", "age", "tenure"]])
print(X[0:5])
y = np.asanyarray(dff['churn'])
print(y[0:5])

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
..      ...   ...      ...     ...  ...     ...    ...       ...       ...   
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0       1.0       0.0   
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0       4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1       9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2       6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3       6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4       7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   
..       ...  ...    ...       ...       ...     ...    ...      ...      ...   
195    17.35  ...    0.0       0.0       0.0     1.0    0.0    2.854    3.199   
196     6.00  ...    0.0       0.0       1.0     1.0    0.0    1.792    3.332   
197     3.85  ...    0.0       0.0       1.0     1.0    0.0    1.348    3.168   
198     8.70  ...    1.0       1.0       1.0     1.0    1.0    2.163    3.866   
199    16.85  ...    0.0       1.0       0.0     0.0    1.0    2.824    3.240   

     lninc  custcat  churn  
0    4.913      4.0    1.0  
1    3.497      1.0    1.0  
2    3.401      3.0    0.0  
3    4.331      4.0    0.0  
4    4.382      3.0    0.0  
..     ...      ...    ...  
195  4.419      3.0    0.0  
196  3.178      3.0    0.0  
197  3.850      3.0    0.0  
198  3.219      4.0    1.0  
199  5.247      2.0    0.0  

[200 rows x 28 columns]

[[ 7.  0.  1. 33. 11.]
 [12.  0.  0. 33. 33.]
 [ 9.  0.  0. 30. 23.]
 [ 5.  1.  1. 35. 38.]
 [14.  0.  1. 35.  7.]]
[1. 1. 0. 0. 0.]


In [ ]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-0.4588971 , -0.88640526,  0.64686916, -0.62595491, -1.13518441],
       [ 0.03454064, -0.88640526, -1.54590766, -0.62595491, -0.11604313],
       [-0.261522  , -0.88640526, -1.54590766, -0.85594447, -0.57928917],
       [-0.65627219,  1.12815215,  0.64686916, -0.47262854,  0.11557989],
       [ 0.23191574, -0.88640526,  0.64686916, -0.47262854, -1.32048283]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 5) (160,)
Test set: (40, 5) (40,)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR


LogisticRegression(C=0.01, solver='liblinear')

In [ ]:
yhat = LR.predict(X_test)
yhat

array([0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 0.])

In [ ]:
arr = confusion_matrix(y_test, yhat)
print((arr[0][0]+arr[1][1])/(arr[0][0]+arr[1][0]+arr[0][1]+arr[1][1]))

0.8
